### ISSUE TITLE
Failure to run sequence model

### ISSUE THREAD

**Issue by sherpashaky** [SEL-Columbia/model_runner#17]
Repeated attempts to run a sequence model uploading a zipped output from NetworkPlanner has failed. Also access to log file is not succesful at the moment.
![image](https://cloud.githubusercontent.com/assets/731717/6401097/bc0fb3de-bdcb-11e4-8d20-90e219c6a94b.png)

**Comment by chrisnatali** [comment]
Closing this in favor of 2 separate issues.  The cause for the log view problem is #18 (a model_runner problem).  

The Sequence failure has to do with the Sequencer and I'm tracking that one here: https://github.com/SEL-Columbia/Sequencer/issues/39
